# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TM_player_board(object):
    def setupUi(self, TM_player_board):
        TM_player_board.setObjectName("TM_player_board")
        TM_player_board.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(TM_player_board)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_15.sizePolicy().hasHeightForWidth())
        self.textBrowser_15.setSizePolicy(sizePolicy)
        self.textBrowser_15.setMinimumSize(QtCore.QSize(60, 0))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.horizontalLayout_25.addWidget(self.textBrowser_15)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setMinimumSize(QtCore.QSize(8, 0))
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setMinimumSize(QtCore.QSize(0, 16))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_49.addWidget(self.label_28)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.new_game = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.new_game.setFont(font)
        self.new_game.setObjectName("new_game")
        self.horizontalLayout_22.addWidget(self.new_game)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        self.TR = QtWidgets.QTextBrowser(self.centralwidget)
        self.TR.setObjectName("TR")
        self.horizontalLayout_22.addWidget(self.TR)
        self.btn_TR_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_TR_plus_1.setFont(font)
        self.btn_TR_plus_1.setObjectName("btn_TR_plus_1")
        self.horizontalLayout_22.addWidget(self.btn_TR_plus_1)
        self.btn_TR_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_TR_minus_1.setFont(font)
        self.btn_TR_minus_1.setObjectName("btn_TR_minus_1")
        self.horizontalLayout_22.addWidget(self.btn_TR_minus_1)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setMinimumSize(QtCore.QSize(100, 0))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        self.Generation = QtWidgets.QTextBrowser(self.centralwidget)
        self.Generation.setObjectName("Generation")
        self.horizontalLayout_23.addWidget(self.Generation)
        self.btn_Go = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_Go.setFont(font)
        self.btn_Go.setObjectName("btn_Go")
        self.horizontalLayout_23.addWidget(self.btn_Go)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout_49.addLayout(self.horizontalLayout_24)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setMinimumSize(QtCore.QSize(0, 18))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_49.addWidget(self.label_25)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.money_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.money_curr.setObjectName("money_curr")
        self.verticalLayout_3.addWidget(self.money_curr)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_money_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_plus_1.setFont(font)
        self.btn_money_curr_plus_1.setObjectName("btn_money_curr_plus_1")
        self.verticalLayout_7.addWidget(self.btn_money_curr_plus_1)
        self.btn_money_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_minus_1.setFont(font)
        self.btn_money_curr_minus_1.setObjectName("btn_money_curr_minus_1")
        self.verticalLayout_7.addWidget(self.btn_money_curr_minus_1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_money_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_plus_3.setFont(font)
        self.btn_money_curr_plus_3.setObjectName("btn_money_curr_plus_3")
        self.verticalLayout_6.addWidget(self.btn_money_curr_plus_3)
        self.btn_money_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_minus_3.setFont(font)
        self.btn_money_curr_minus_3.setObjectName("btn_money_curr_minus_3")
        self.verticalLayout_6.addWidget(self.btn_money_curr_minus_3)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_money_curr_plus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_plus_10.setFont(font)
        self.btn_money_curr_plus_10.setObjectName("btn_money_curr_plus_10")
        self.verticalLayout.addWidget(self.btn_money_curr_plus_10)
        self.btn_money_curr_minus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_curr_minus_10.setFont(font)
        self.btn_money_curr_minus_10.setObjectName("btn_money_curr_minus_10")
        self.verticalLayout.addWidget(self.btn_money_curr_minus_10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.money_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.money_prod.setObjectName("money_prod")
        self.verticalLayout_4.addWidget(self.money_prod)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_money_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_prod_plus_1.setFont(font)
        self.btn_money_prod_plus_1.setObjectName("btn_money_prod_plus_1")
        self.verticalLayout_8.addWidget(self.btn_money_prod_plus_1)
        self.btn_money_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_prod_minus_1.setFont(font)
        self.btn_money_prod_minus_1.setObjectName("btn_money_prod_minus_1")
        self.verticalLayout_8.addWidget(self.btn_money_prod_minus_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_money_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_prod_plus_3.setFont(font)
        self.btn_money_prod_plus_3.setObjectName("btn_money_prod_plus_3")
        self.verticalLayout_2.addWidget(self.btn_money_prod_plus_3)
        self.btn_money_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_money_prod_minus_3.setFont(font)
        self.btn_money_prod_minus_3.setObjectName("btn_money_prod_minus_3")
        self.verticalLayout_2.addWidget(self.btn_money_prod_minus_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setMinimumSize(QtCore.QSize(100, 0))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.plant_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.plant_curr.setObjectName("plant_curr")
        self.verticalLayout_10.addWidget(self.plant_curr)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btn_plant_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_plus_1.setFont(font)
        self.btn_plant_curr_plus_1.setObjectName("btn_plant_curr_plus_1")
        self.verticalLayout_11.addWidget(self.btn_plant_curr_plus_1)
        self.btn_plant_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_minus_1.setFont(font)
        self.btn_plant_curr_minus_1.setObjectName("btn_plant_curr_minus_1")
        self.verticalLayout_11.addWidget(self.btn_plant_curr_minus_1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_plant_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_plus_3.setFont(font)
        self.btn_plant_curr_plus_3.setObjectName("btn_plant_curr_plus_3")
        self.verticalLayout_12.addWidget(self.btn_plant_curr_plus_3)
        self.btn_plant_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_minus_3.setFont(font)
        self.btn_plant_curr_minus_3.setObjectName("btn_plant_curr_minus_3")
        self.verticalLayout_12.addWidget(self.btn_plant_curr_minus_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_plant_curr_plus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_plus_8.setFont(font)
        self.btn_plant_curr_plus_8.setObjectName("btn_plant_curr_plus_8")
        self.verticalLayout_13.addWidget(self.btn_plant_curr_plus_8)
        self.btn_plant_curr_minus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_curr_minus_8.setFont(font)
        self.btn_plant_curr_minus_8.setObjectName("btn_plant_curr_minus_8")
        self.verticalLayout_13.addWidget(self.btn_plant_curr_minus_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.plant_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.plant_prod.setObjectName("plant_prod")
        self.verticalLayout_14.addWidget(self.plant_prod)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.btn_plant_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_prod_plus_1.setFont(font)
        self.btn_plant_prod_plus_1.setObjectName("btn_plant_prod_plus_1")
        self.verticalLayout_15.addWidget(self.btn_plant_prod_plus_1)
        self.btn_plant_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_prod_minus_1.setFont(font)
        self.btn_plant_prod_minus_1.setObjectName("btn_plant_prod_minus_1")
        self.verticalLayout_15.addWidget(self.btn_plant_prod_minus_1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.btn_plant_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_prod_plus_3.setFont(font)
        self.btn_plant_prod_plus_3.setObjectName("btn_plant_prod_plus_3")
        self.verticalLayout_16.addWidget(self.btn_plant_prod_plus_3)
        self.btn_plant_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_plant_prod_minus_3.setFont(font)
        self.btn_plant_prod_minus_3.setObjectName("btn_plant_prod_minus_3")
        self.verticalLayout_16.addWidget(self.btn_plant_prod_minus_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_16)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_49.addLayout(self.horizontalLayout_7)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setMinimumSize(QtCore.QSize(0, 18))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_49.addWidget(self.label_26)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_17.addWidget(self.label_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_18.addWidget(self.label_8)
        self.steel_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.steel_curr.setObjectName("steel_curr")
        self.verticalLayout_18.addWidget(self.steel_curr)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.btn_steel_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_plus_1.setFont(font)
        self.btn_steel_curr_plus_1.setObjectName("btn_steel_curr_plus_1")
        self.verticalLayout_19.addWidget(self.btn_steel_curr_plus_1)
        self.btn_steel_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_minus_1.setFont(font)
        self.btn_steel_curr_minus_1.setObjectName("btn_steel_curr_minus_1")
        self.verticalLayout_19.addWidget(self.btn_steel_curr_minus_1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.btn_steel_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_plus_3.setFont(font)
        self.btn_steel_curr_plus_3.setObjectName("btn_steel_curr_plus_3")
        self.verticalLayout_20.addWidget(self.btn_steel_curr_plus_3)
        self.btn_steel_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_minus_3.setFont(font)
        self.btn_steel_curr_minus_3.setObjectName("btn_steel_curr_minus_3")
        self.verticalLayout_20.addWidget(self.btn_steel_curr_minus_3)
        self.horizontalLayout_10.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.btn_steel_curr_plus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_plus_10.setFont(font)
        self.btn_steel_curr_plus_10.setObjectName("btn_steel_curr_plus_10")
        self.verticalLayout_21.addWidget(self.btn_steel_curr_plus_10)
        self.btn_steel_curr_minus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_curr_minus_10.setFont(font)
        self.btn_steel_curr_minus_10.setObjectName("btn_steel_curr_minus_10")
        self.verticalLayout_21.addWidget(self.btn_steel_curr_minus_10)
        self.horizontalLayout_10.addLayout(self.verticalLayout_21)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_22.addWidget(self.label_9)
        self.steel_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.steel_prod.setObjectName("steel_prod")
        self.verticalLayout_22.addWidget(self.steel_prod)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.btn_steel_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_prod_plus_1.setFont(font)
        self.btn_steel_prod_plus_1.setObjectName("btn_steel_prod_plus_1")
        self.verticalLayout_23.addWidget(self.btn_steel_prod_plus_1)
        self.btn_steel_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_prod_minus_1.setFont(font)
        self.btn_steel_prod_minus_1.setObjectName("btn_steel_prod_minus_1")
        self.verticalLayout_23.addWidget(self.btn_steel_prod_minus_1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.btn_steel_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_prod_plus_3.setFont(font)
        self.btn_steel_prod_plus_3.setObjectName("btn_steel_prod_plus_3")
        self.verticalLayout_24.addWidget(self.btn_steel_prod_plus_3)
        self.btn_steel_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_steel_prod_minus_3.setFont(font)
        self.btn_steel_prod_minus_3.setObjectName("btn_steel_prod_minus_3")
        self.verticalLayout_24.addWidget(self.btn_steel_prod_minus_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_24)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_25.addWidget(self.label_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_26.addWidget(self.label_11)
        self.energy_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.energy_curr.setObjectName("energy_curr")
        self.verticalLayout_26.addWidget(self.energy_curr)
        self.horizontalLayout_13.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.btn_energy_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_plus_1.setFont(font)
        self.btn_energy_curr_plus_1.setObjectName("btn_energy_curr_plus_1")
        self.verticalLayout_27.addWidget(self.btn_energy_curr_plus_1)
        self.btn_energy_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_minus_1.setFont(font)
        self.btn_energy_curr_minus_1.setObjectName("btn_energy_curr_minus_1")
        self.verticalLayout_27.addWidget(self.btn_energy_curr_minus_1)
        self.horizontalLayout_13.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.btn_energy_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_plus_3.setFont(font)
        self.btn_energy_curr_plus_3.setObjectName("btn_energy_curr_plus_3")
        self.verticalLayout_28.addWidget(self.btn_energy_curr_plus_3)
        self.btn_energy_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_minus_3.setFont(font)
        self.btn_energy_curr_minus_3.setObjectName("btn_energy_curr_minus_3")
        self.verticalLayout_28.addWidget(self.btn_energy_curr_minus_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.btn_energy_curr_plus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_plus_8.setFont(font)
        self.btn_energy_curr_plus_8.setObjectName("btn_energy_curr_plus_8")
        self.verticalLayout_29.addWidget(self.btn_energy_curr_plus_8)
        self.btn_energy_curr_minus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_curr_minus_8.setFont(font)
        self.btn_energy_curr_minus_8.setObjectName("btn_energy_curr_minus_8")
        self.verticalLayout_29.addWidget(self.btn_energy_curr_minus_8)
        self.horizontalLayout_13.addLayout(self.verticalLayout_29)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_30.addWidget(self.label_12)
        self.energy_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.energy_prod.setObjectName("energy_prod")
        self.verticalLayout_30.addWidget(self.energy_prod)
        self.horizontalLayout_14.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.btn_energy_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_prod_plus_1.setFont(font)
        self.btn_energy_prod_plus_1.setObjectName("btn_energy_prod_plus_1")
        self.verticalLayout_31.addWidget(self.btn_energy_prod_plus_1)
        self.btn_energy_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_prod_minus_1.setFont(font)
        self.btn_energy_prod_minus_1.setObjectName("btn_energy_prod_minus_1")
        self.verticalLayout_31.addWidget(self.btn_energy_prod_minus_1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.btn_energy_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_prod_plus_3.setFont(font)
        self.btn_energy_prod_plus_3.setObjectName("btn_energy_prod_plus_3")
        self.verticalLayout_32.addWidget(self.btn_energy_prod_plus_3)
        self.btn_energy_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_energy_prod_minus_3.setFont(font)
        self.btn_energy_prod_minus_3.setObjectName("btn_energy_prod_minus_3")
        self.verticalLayout_32.addWidget(self.btn_energy_prod_minus_3)
        self.horizontalLayout_14.addLayout(self.verticalLayout_32)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_14)
        self.verticalLayout_25.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8.addLayout(self.verticalLayout_25)
        self.verticalLayout_49.addLayout(self.horizontalLayout_8)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setMinimumSize(QtCore.QSize(0, 18))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_49.addWidget(self.label_27)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_33.addWidget(self.label_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_34.addWidget(self.label_14)
        self.titian_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.titian_curr.setObjectName("titian_curr")
        self.verticalLayout_34.addWidget(self.titian_curr)
        self.horizontalLayout_17.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.btn_titian_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_plus_1.setFont(font)
        self.btn_titian_curr_plus_1.setObjectName("btn_titian_curr_plus_1")
        self.verticalLayout_35.addWidget(self.btn_titian_curr_plus_1)
        self.btn_titian_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_minus_1.setFont(font)
        self.btn_titian_curr_minus_1.setObjectName("btn_titian_curr_minus_1")
        self.verticalLayout_35.addWidget(self.btn_titian_curr_minus_1)
        self.horizontalLayout_17.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.btn_titian_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_plus_3.setFont(font)
        self.btn_titian_curr_plus_3.setObjectName("btn_titian_curr_plus_3")
        self.verticalLayout_36.addWidget(self.btn_titian_curr_plus_3)
        self.btn_titian_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_minus_3.setFont(font)
        self.btn_titian_curr_minus_3.setObjectName("btn_titian_curr_minus_3")
        self.verticalLayout_36.addWidget(self.btn_titian_curr_minus_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.btn_titian_curr_plus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_plus_10.setFont(font)
        self.btn_titian_curr_plus_10.setObjectName("btn_titian_curr_plus_10")
        self.verticalLayout_37.addWidget(self.btn_titian_curr_plus_10)
        self.btn_titian_curr_minus_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_curr_minus_10.setFont(font)
        self.btn_titian_curr_minus_10.setObjectName("btn_titian_curr_minus_10")
        self.verticalLayout_37.addWidget(self.btn_titian_curr_minus_10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_37)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_38.addWidget(self.label_15)
        self.titian_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.titian_prod.setObjectName("titian_prod")
        self.verticalLayout_38.addWidget(self.titian_prod)
        self.horizontalLayout_18.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.btn_titian_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_prod_plus_1.setFont(font)
        self.btn_titian_prod_plus_1.setObjectName("btn_titian_prod_plus_1")
        self.verticalLayout_39.addWidget(self.btn_titian_prod_plus_1)
        self.btn_titian_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_prod_minus_1.setFont(font)
        self.btn_titian_prod_minus_1.setObjectName("btn_titian_prod_minus_1")
        self.verticalLayout_39.addWidget(self.btn_titian_prod_minus_1)
        self.horizontalLayout_18.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.btn_titian_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_prod_plus_3.setFont(font)
        self.btn_titian_prod_plus_3.setObjectName("btn_titian_prod_plus_3")
        self.verticalLayout_40.addWidget(self.btn_titian_prod_plus_3)
        self.btn_titian_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_titian_prod_minus_3.setFont(font)
        self.btn_titian_prod_minus_3.setObjectName("btn_titian_prod_minus_3")
        self.verticalLayout_40.addWidget(self.btn_titian_prod_minus_3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_40)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout_33.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15.addLayout(self.verticalLayout_33)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setMinimumSize(QtCore.QSize(100, 0))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_41.addWidget(self.label_16)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_42.addWidget(self.label_17)
        self.heat_curr = QtWidgets.QTextBrowser(self.centralwidget)
        self.heat_curr.setObjectName("heat_curr")
        self.verticalLayout_42.addWidget(self.heat_curr)
        self.horizontalLayout_20.addLayout(self.verticalLayout_42)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.btn_heat_curr_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_plus_1.setFont(font)
        self.btn_heat_curr_plus_1.setObjectName("btn_heat_curr_plus_1")
        self.verticalLayout_43.addWidget(self.btn_heat_curr_plus_1)
        self.btn_heat_curr_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_minus_1.setFont(font)
        self.btn_heat_curr_minus_1.setObjectName("btn_heat_curr_minus_1")
        self.verticalLayout_43.addWidget(self.btn_heat_curr_minus_1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_43)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.btn_heat_curr_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_plus_3.setFont(font)
        self.btn_heat_curr_plus_3.setObjectName("btn_heat_curr_plus_3")
        self.verticalLayout_44.addWidget(self.btn_heat_curr_plus_3)
        self.btn_heat_curr_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_minus_3.setFont(font)
        self.btn_heat_curr_minus_3.setObjectName("btn_heat_curr_minus_3")
        self.verticalLayout_44.addWidget(self.btn_heat_curr_minus_3)
        self.horizontalLayout_20.addLayout(self.verticalLayout_44)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.btn_heat_curr_plus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_plus_8.setFont(font)
        self.btn_heat_curr_plus_8.setObjectName("btn_heat_curr_plus_8")
        self.verticalLayout_45.addWidget(self.btn_heat_curr_plus_8)
        self.btn_heat_curr_minus_8 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_curr_minus_8.setFont(font)
        self.btn_heat_curr_minus_8.setObjectName("btn_heat_curr_minus_8")
        self.verticalLayout_45.addWidget(self.btn_heat_curr_minus_8)
        self.horizontalLayout_20.addLayout(self.verticalLayout_45)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_46.addWidget(self.label_18)
        self.heat_prod = QtWidgets.QTextBrowser(self.centralwidget)
        self.heat_prod.setObjectName("heat_prod")
        self.verticalLayout_46.addWidget(self.heat_prod)
        self.horizontalLayout_21.addLayout(self.verticalLayout_46)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.btn_heat_prod_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_prod_plus_1.setFont(font)
        self.btn_heat_prod_plus_1.setObjectName("btn_heat_prod_plus_1")
        self.verticalLayout_47.addWidget(self.btn_heat_prod_plus_1)
        self.btn_heat_prod_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_prod_minus_1.setFont(font)
        self.btn_heat_prod_minus_1.setObjectName("btn_heat_prod_minus_1")
        self.verticalLayout_47.addWidget(self.btn_heat_prod_minus_1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_47)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.btn_heat_prod_plus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_prod_plus_3.setFont(font)
        self.btn_heat_prod_plus_3.setObjectName("btn_heat_prod_plus_3")
        self.verticalLayout_48.addWidget(self.btn_heat_prod_plus_3)
        self.btn_heat_prod_minus_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btn_heat_prod_minus_3.setFont(font)
        self.btn_heat_prod_minus_3.setObjectName("btn_heat_prod_minus_3")
        self.verticalLayout_48.addWidget(self.btn_heat_prod_minus_3)
        self.horizontalLayout_21.addLayout(self.verticalLayout_48)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout_41.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_15.addLayout(self.verticalLayout_41)
        self.verticalLayout_49.addLayout(self.horizontalLayout_15)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setMinimumSize(QtCore.QSize(0, 16))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_49.addWidget(self.label_29)
        self.horizontalLayout_25.addLayout(self.verticalLayout_49)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setMinimumSize(QtCore.QSize(8, 0))
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_25.addWidget(self.label_31)
        TM_player_board.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TM_player_board)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        TM_player_board.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TM_player_board)
        self.statusbar.setObjectName("statusbar")
        TM_player_board.setStatusBar(self.statusbar)

        self.retranslateUi(TM_player_board)
        self.new_game.clicked.connect(TM_player_board.start_new_game)
        self.btn_TR_plus_1.clicked.connect(TM_player_board.tr_add_1)
        self.btn_TR_minus_1.clicked.connect(TM_player_board.tr_minus_1)
        self.btn_Go.clicked.connect(TM_player_board.gen_go)
        self.btn_money_curr_plus_1.clicked.connect(TM_player_board.money_curr_plus_1)
        self.btn_money_curr_plus_3.clicked.connect(TM_player_board.money_curr_plus_3)
        self.btn_money_curr_plus_10.clicked.connect(TM_player_board.money_curr_plus_10)
        self.btn_money_curr_minus_1.clicked.connect(TM_player_board.money_curr_minus_1)
        self.btn_money_curr_minus_3.clicked.connect(TM_player_board.money_curr_minus_3)
        self.btn_money_curr_minus_10.clicked.connect(TM_player_board.money_curr_minus_10)
        self.btn_money_prod_plus_1.clicked.connect(TM_player_board.money_prod_plus_1)
        self.btn_money_prod_plus_3.clicked.connect(TM_player_board.money_prod_plus_3)
        self.btn_money_prod_minus_1.clicked.connect(TM_player_board.money_prod_minus_1)
        self.btn_money_prod_minus_3.clicked.connect(TM_player_board.money_prod_minus_3)
        self.btn_steel_curr_plus_1.clicked.connect(TM_player_board.steel_curr_plus_1)
        self.btn_steel_curr_plus_3.clicked.connect(TM_player_board.steel_curr_plus_3)
        self.btn_steel_curr_plus_10.clicked.connect(TM_player_board.steel_curr_plus_10)
        self.btn_steel_curr_minus_1.clicked.connect(TM_player_board.steel_curr_minus_1)
        self.btn_steel_curr_minus_3.clicked.connect(TM_player_board.steel_curr_minus_3)
        self.btn_steel_curr_minus_10.clicked.connect(TM_player_board.steel_curr_minus_10)
        self.btn_steel_prod_plus_1.clicked.connect(TM_player_board.steel_prod_plus_1)
        self.btn_steel_prod_plus_3.clicked.connect(TM_player_board.steel_prod_plus_3)
        self.btn_steel_prod_minus_1.clicked.connect(TM_player_board.steel_prod_minus_1)
        self.btn_steel_prod_minus_3.clicked.connect(TM_player_board.steel_prod_minus_3)
        self.btn_titian_curr_plus_1.clicked.connect(TM_player_board.titian_curr_plus_1)
        self.btn_titian_curr_plus_3.clicked.connect(TM_player_board.titian_curr_plus_3)
        self.btn_titian_curr_plus_10.clicked.connect(TM_player_board.titian_curr_plus_10)
        self.btn_titian_curr_minus_1.clicked.connect(TM_player_board.titian_curr_minus_1)
        self.btn_titian_curr_minus_3.clicked.connect(TM_player_board.titian_curr_minus_3)
        self.btn_titian_curr_minus_10.clicked.connect(TM_player_board.titian_curr_minus_10)
        self.btn_titian_prod_plus_1.clicked.connect(TM_player_board.titian_prod_plus_1)
        self.btn_titian_prod_plus_3.clicked.connect(TM_player_board.titian_prod_plus_3)
        self.btn_titian_prod_minus_1.clicked.connect(TM_player_board.titian_prod_minus_1)
        self.btn_titian_prod_minus_3.clicked.connect(TM_player_board.titian_prod_minus_3)
        self.btn_plant_curr_plus_1.clicked.connect(TM_player_board.plant_curr_plus_1)
        self.btn_plant_curr_plus_3.clicked.connect(TM_player_board.plant_curr_plus_3)
        self.btn_plant_curr_plus_8.clicked.connect(TM_player_board.plant_curr_plus_8)
        self.btn_plant_curr_minus_1.clicked.connect(TM_player_board.plant_curr_minus_1)
        self.btn_plant_curr_minus_3.clicked.connect(TM_player_board.plant_curr_minus_3)
        self.btn_plant_curr_minus_8.clicked.connect(TM_player_board.plant_curr_minus_8)
        self.btn_plant_prod_plus_1.clicked.connect(TM_player_board.plant_prod_plus_1)
        self.btn_plant_prod_plus_3.clicked.connect(TM_player_board.plant_prod_plus_3)
        self.btn_plant_prod_minus_1.clicked.connect(TM_player_board.plant_prod_minus_1)
        self.btn_plant_prod_minus_3.clicked.connect(TM_player_board.plant_prod_minus_3)
        self.btn_energy_curr_plus_1.clicked.connect(TM_player_board.energy_curr_plus_1)
        self.btn_energy_curr_plus_3.clicked.connect(TM_player_board.energy_curr_plus_3)
        self.btn_energy_curr_plus_8.clicked.connect(TM_player_board.energy_curr_plus_8)
        self.btn_energy_curr_minus_1.clicked.connect(TM_player_board.energy_curr_minus_1)
        self.btn_energy_curr_minus_3.clicked.connect(TM_player_board.energy_curr_minus_3)
        self.btn_energy_curr_minus_8.clicked.connect(TM_player_board.energy_curr_minus_8)
        self.btn_energy_prod_plus_1.clicked.connect(TM_player_board.energy_prod_plus_1)
        self.btn_energy_prod_plus_3.clicked.connect(TM_player_board.energy_prod_plus_3)
        self.btn_energy_prod_minus_1.clicked.connect(TM_player_board.energy_prod_minus_1)
        self.btn_energy_prod_minus_3.clicked.connect(TM_player_board.energy_prod_minus_3)
        self.btn_heat_curr_plus_1.clicked.connect(TM_player_board.heat_curr_plus_1)
        self.btn_heat_curr_plus_3.clicked.connect(TM_player_board.heat_curr_plus_3)
        self.btn_heat_curr_plus_8.clicked.connect(TM_player_board.heat_curr_plus_8)
        self.btn_heat_curr_minus_1.clicked.connect(TM_player_board.heat_curr_minus_1)
        self.btn_heat_curr_minus_3.clicked.connect(TM_player_board.heat_curr_minus_3)
        self.btn_heat_curr_minus_8.clicked.connect(TM_player_board.heat_curr_minus_8)
        self.btn_heat_prod_plus_1.clicked.connect(TM_player_board.heat_prod_plus_1)
        self.btn_heat_prod_plus_3.clicked.connect(TM_player_board.heat_prod_plus_3)
        self.btn_heat_prod_minus_1.clicked.connect(TM_player_board.heat_prod_minus_1)
        self.btn_heat_prod_minus_3.clicked.connect(TM_player_board.heat_prod_minus_3)
        QtCore.QMetaObject.connectSlotsByName(TM_player_board)

    def retranslateUi(self, TM_player_board):
        _translate = QtCore.QCoreApplication.translate
        TM_player_board.setWindowTitle(_translate("TM_player_board", "MainWindow"))
        self.textBrowser_15.setHtml(_translate("TM_player_board", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">T</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">E</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">R</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">R</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">A</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">F</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">O</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">R</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">M</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">I</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">N</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">G</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">M</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">A</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">R</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">S</span></p></body></html>"))
        self.new_game.setText(_translate("TM_player_board", "NewGame"))
        self.label_20.setText(_translate("TM_player_board", "TR"))
        self.btn_TR_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_TR_minus_1.setText(_translate("TM_player_board", "-1"))
        self.label_21.setText(_translate("TM_player_board", "Generation"))
        self.btn_Go.setText(_translate("TM_player_board", "GO"))
        self.label.setText(_translate("TM_player_board", "Money"))
        self.label_3.setText(_translate("TM_player_board", "Curr"))
        self.btn_money_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_money_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_money_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_money_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_money_curr_plus_10.setText(_translate("TM_player_board", "+10"))
        self.btn_money_curr_minus_10.setText(_translate("TM_player_board", "-10"))
        self.label_2.setText(_translate("TM_player_board", "Prod"))
        self.btn_money_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_money_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_money_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_money_prod_minus_3.setText(_translate("TM_player_board", "-3"))
        self.label_4.setText(_translate("TM_player_board", "Plant"))
        self.label_5.setText(_translate("TM_player_board", "Curr"))
        self.plant_curr.setHtml(_translate("TM_player_board", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_plant_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_plant_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_plant_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_plant_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_plant_curr_plus_8.setText(_translate("TM_player_board", "+8"))
        self.btn_plant_curr_minus_8.setText(_translate("TM_player_board", "-8"))
        self.label_6.setText(_translate("TM_player_board", "Prod"))
        self.btn_plant_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_plant_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_plant_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_plant_prod_minus_3.setText(_translate("TM_player_board", "-3"))
        self.label_7.setText(_translate("TM_player_board", "Steel"))
        self.label_8.setText(_translate("TM_player_board", "Curr"))
        self.btn_steel_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_steel_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_steel_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_steel_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_steel_curr_plus_10.setText(_translate("TM_player_board", "+10"))
        self.btn_steel_curr_minus_10.setText(_translate("TM_player_board", "-10"))
        self.label_9.setText(_translate("TM_player_board", "Prod"))
        self.btn_steel_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_steel_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_steel_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_steel_prod_minus_3.setText(_translate("TM_player_board", "-3"))
        self.label_10.setText(_translate("TM_player_board", "Energy"))
        self.label_11.setText(_translate("TM_player_board", "Curr"))
        self.btn_energy_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_energy_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_energy_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_energy_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_energy_curr_plus_8.setText(_translate("TM_player_board", "+8"))
        self.btn_energy_curr_minus_8.setText(_translate("TM_player_board", "-8"))
        self.label_12.setText(_translate("TM_player_board", "Prod"))
        self.btn_energy_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_energy_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_energy_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_energy_prod_minus_3.setText(_translate("TM_player_board", "-3"))
        self.label_13.setText(_translate("TM_player_board", "Titianium"))
        self.label_14.setText(_translate("TM_player_board", "Curr"))
        self.btn_titian_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_titian_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_titian_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_titian_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_titian_curr_plus_10.setText(_translate("TM_player_board", "+10"))
        self.btn_titian_curr_minus_10.setText(_translate("TM_player_board", "-10"))
        self.label_15.setText(_translate("TM_player_board", "Prod"))
        self.btn_titian_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_titian_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_titian_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_titian_prod_minus_3.setText(_translate("TM_player_board", "-3"))
        self.label_16.setText(_translate("TM_player_board", "Heat"))
        self.label_17.setText(_translate("TM_player_board", "Curr"))
        self.btn_heat_curr_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_heat_curr_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_heat_curr_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_heat_curr_minus_3.setText(_translate("TM_player_board", "-3"))
        self.btn_heat_curr_plus_8.setText(_translate("TM_player_board", "+8"))
        self.btn_heat_curr_minus_8.setText(_translate("TM_player_board", "-8"))
        self.label_18.setText(_translate("TM_player_board", "Prod"))
        self.btn_heat_prod_plus_1.setText(_translate("TM_player_board", "+1"))
        self.btn_heat_prod_minus_1.setText(_translate("TM_player_board", "-1"))
        self.btn_heat_prod_plus_3.setText(_translate("TM_player_board", "+3"))
        self.btn_heat_prod_minus_3.setText(_translate("TM_player_board", "-3"))

